### ISSUE TITLE
Settings migration from old cutecom

### ISSUE THREAD

**Issue by roman-khimov** [neundorf/CuteCom#13]
I see that new (0.30+) CuteCom uses CuteCom5 as the application name, while old one (pre-0.30) used CuteCom, so they write their configuration into different files and from the comment in `mainwindow.cpp` it seems to be done intentionally.

Now the two questions are: are these formats compatible (looks like not, but) and whether there are any ways to migrate old settings to new CuteCom?

**Comment by cyc1ingsir** [comment]
No, it's not compatible. (since the previous CuteCom doesn't know about sessions).
Regarding migration
One could create a new config file and a "Default" session within, copying some settings like the History and a few other settings.
I thought about implementing it but considered it not worth it in the end. As this would be used one time after upgrading only, I didn't want to make the code more complicated than necessary.
However an update script could do this.
