### ISSUE TITLE
could write on port drop down

### ISSUE THREAD

**Issue by kwendenarmo** [neundorf/CuteCom#44]
It would be nice to have the possibility of manually write the port that you want to use, apart from being able to choose it from the drop down. When the port is a virtual socket, it not listed and can not be selected.

**Comment by cyc1ingsir** [comment]
The port selection combo box list all devices Qt's Serial Port knows about. Adding or removing an USB to serial converter adds and removes this device from the list.
To test if SerialPort can handle the virtual device at all, you could tinker with the config file ` ~/.config/CuteCom/CuteCom5.conf` 
Just change the appropriate line within `[sessions]` e.g.
`1\Device=/dev/<your device`
(If you defined more than one session, you need to change the line of the last used session)
CuteCom doesn't check the presence of the selected device on startup.
Let us know if you are then able to talk to that device.

**Comment by kwendenarmo** [comment]
Thanks for the reply. I have seen the option but I have not been able to test it with the virtual device yet.
In previous versions of cutecom was allowed to write directly in the combo box, is there any reason why this version has been disabled?
Editing a file can be a pain to deal with this in a regular way.

**Comment by cyc1ingsir** [comment]
The current version of CuteCom is more a less a complete rewrite porting it to Qt 5.x. At least concerning the UI.
The previous version didn't use QtSerialPort (http://doc.qt.io/qt-5/qtserialport-index.html) either since AFAIR this was introduced with 5.x too. Listing ports supported by QtSerialPort module only, should prevent user error and makes choosing a port easier.
The question now is: Does QtSerialPort recognise your port or doesn't it. If it does, the question is, why the port is not listed. A fix upstream would then be preferable.
In case it doesn't, solving the problem would be even more complicated since the port needed to be talked too with a different method. 
Btw: If you don't mind building this example (http://doc.qt.io/qt-5/qtserialport-terminal-example.html) you could try if this works with your port.
Editing the config file is just the first step in hopefully tackling the problem.

**Comment by lujji** [comment]
@cyc1ingsir I can confirm this issue. You can test it by creating a virtual pair with socat:
`socat PTY,link=/dev/ttyP0 PTY,link=/dev/ttyP1`
`chmod 0666 /dev/ttyP0 /devttyP1`
These ports are not listed in the drop-down menu but can be accessed if I modify .conf file.

**Comment by HoracioDos** [comment]
Hello! 
I started to use direwolf (AX.25 packet modem/TNC and APRS encoder/decoder) It supports KISS TNC on virtual serial ports. I would like to use cutecom for this. I'll try @lujji workaround.
Thanks

**Comment by cyc1ingsir** [comment]
Issue moved to https://gitlab.com/cutecom/cutecom/issues/44
