### ISSUE TITLE
Add prebuilt app versions to the repo

### ISSUE THREAD

**Issue by LeonidKokhnovich** [neundorf/CuteCom#61]
Thank you for the great software! It would be really great if people could download a prebuilt app version (Windows/Mac) without the hassle of building it themselves.

**Comment by cyc1ingsir** [comment]
Glad, you enjoy using the software.
However, providing binary artifacts of CuteCom is out of scope of this project. I haven neither of this systems available and since neither is freely available one could not even run those virtualized without extra cost.
AFAIK Travis CI supports OSX builds and AppVeyor supports Windows builds. Someone needed to evaluate if these platforms could be used for creating distributables. I believe these options are available on paid for subscriptions on either platform. (OSX on Travis CI might be available for open source projects too)
To setup a connected plan on Travis CI for CuteCom, this repo needs to be transfered to an organisation account previously as suggested in #58.
There is yet another aspect to be considered: How could one be sure, the provided binaries don't contain any malware. This really is out of scope of this project. Sorry, in the end building one's own binary seems a lot less hazzle.
As always: Providing PRs to ensure a version can be build on your OS of choice are welcome. A windows PR was provided not long ago. I'm not sure, CuteCom is buildable on OSX in the current state.
