### ISSUE TITLE
QNetworkDatagram requires QT 5.8

### ISSUE THREAD

**Issue by andrasbiro** [neundorf/CuteCom#75]
See here: https://doc.qt.io/qt-5.9/qnetworkdatagram.html

This makes the readme's 5.1 requirement outdated, and complicated to build on debian stable, which has 5.3

The requirement was added with #71 by @dimtass

**Comment by dimtass** [comment]
@andrasbiro I'll have a look at this and probably use the older UDP sockets.

**Comment by sza2** [comment]
Just FYI, actually Debian stable is "9" / Stretch, which uses Qt 5.7 but the same issue exists.

Debian 8 / Jessie uses Qt 5.3  - although it was possible to compile even with Qt5.3 prior.

**Comment by dimtass** [comment]
Thanks, I'm going to change this with the QUdpSocket, which I was using with 4.x and it's stable and preforms well.
http://doc.qt.io/archives/qt-4.8/qudpsocket.html

**Comment by dimtass** [comment]
@cyc1ingsir I've had a look at the QT5 versions and it seems that the minimum version in the README should be 5.2 as also the QCommandLineParser class, used in main.c is introduced after 5.2.
Therefore, I'll also update the minimum version to 5.2 and use this for testing.
http://doc.qt.io/qt-5/qcommandlineparser.html

**Comment by dimtass** [comment]
@andrasbiro @sza2 @cyc1ingsir 

- I've removed QNetworkDiagram and tested with 5.2 and it builds/works on my system
- I've updated the README and now the min version is 5.2.
- Increased the height of the byte counter plugin
- Moved the `Plugins` menu before `Help`
- Added `P` as a shortcut for `Plugins` menu

**Comment by cyc1ingsir** [comment]
Hi all,

in general I'd say it would be good to still support Debian 8 / Jessie and therefor set the minimum Qt version to 5.3 (thanks @sza2 for looking that up). 
Personally I'm not using Debian on my desktop machine so I wouldn't know unfortunately.
The problem is, the Travis-CI checks against 5.9.3  (https://github.com/neundorf/CuteCom/blob/master/.travis.yml)
So this has some inconsistency, I've got to admit.
The next problem is, I can't connect Travis with this very repository. I'll add the my newest thoughts of this over at #58 within a minute. I would be happy about comments on this.

**Comment by cyc1ingsir** [comment]
I think, this has been solved.
In case not, reopen at https://gitlab.com/cutecom/cutecom/issues/75

**Comment by sza2** [comment]
I was able to compile on Debian 9.
